version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: "falkon"
    ports:
        - 9200:9200
        - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
        ELASTICSEARCH_USERNAME: "vova"
        ELASTICSEARCH_PASSWORD: "falkon"
        xpack.security.enabled: "true"
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch